name: Build & Deploy
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: npm install
    - run: npm run hoist
    - run: npm run build
    - run: npm run bundle
    - run: npm run bundle:min
    - run: npm run doc
    - run: npm run coverage
    - run: npm i coverage-badges-cli -g
    - run: coverage-badges
    - run: cp -rp coverage website/build

    - run: npm install @jsdevtools/npm-publish -g
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-alpha/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-block/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-convert/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-compact/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-colorful/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-circle/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-github/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-chrome/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-editable-input/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-editable-input-hsla/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-editable-input-rgba/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-hue/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-name/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-material/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-saturation/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-shade-slider/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-sketch/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-slider/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-swatch/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/color-wheel/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/drag-event-interactive/package.json

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.6
      with:
        package-path: ./packages/color/package.json

    - name: get tag version
      id: tag_version
      uses: jaywcjlove/changelog-generator@v1.5.0

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/build

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.5.0
      if: steps.create_tag.outputs.successful
      with:
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-color@${{steps.create_tag.outputs.versionNumber}}/file/README.md) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/@uiw/react-color)](https://bundlephobia.com/result?p=@uiw/react-color@${{steps.create_tag.outputs.versionNumber}})
          
          Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/uiwjs/react-color/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
          Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  

          ```bash
          npm i @uiw/react-color@${{steps.create_tag.outputs.versionNumber}}
          ```

          ${{ steps.changelog.outputs.changelog }}

    # - name: Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}